#!/bin/bash

# Author: Talha Khan <tkhan@5gcomms.com>, 24/08/2020

# Usage helper function
display_usage() {
        echo "This script searches the UniFi AP by MAC address and returns site information."
        echo "The MAC address must be supplied in colon-hexadecimal notation (01:23:45:67:78:9a)."
        echo -e "Usage: $0 <UniFi AP MAC>\n"
}

# Display usage and exit if no parameters supplied
if [[ -z $1 ]]
then
        echo -e "Error: No MAC address supplied.\n"
        display_usage
        exit 1
fi

# Display usage and exit if help requested
if [[ ( $1 == "-h" ) || ( $1 == "--help" ) ]]
then
        display_usage
        exit 0
fi

# Validate MAC address supplied
if ! [[ $1 =~ ^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$ ]]
then
        echo -e "Error: Invalid MAC address.\n"
        display_usage
        exit 1
fi

# Force MAC address to lowercase for DB comparison
mac=${1,,}

# Find AP
site_objid=$(mongo --quiet --port 27117 --eval 'db.getSiblingDB("ace").device.find({"mac":"'"$mac"'"}).forEach(function(x){print(x.site_id)})')

if [[ -z $site_objid ]]
then
        echo -e "Error: AP MAC $mac not found in UniFi database."
        exit 1
fi

# Find site name and id using object id previously retrieved
site_name=$(mongo --quiet --port 27117 --eval 'db.getSiblingDB("ace").site.find({"_id":ObjectId("'"$site_objid"'")}).forEach(function(x){print(x.desc)})')
site_id=$(mongo --quiet --port 27117 --eval 'db.getSiblingDB("ace").site.find({"_id":ObjectId("'"$site_objid"'")}).forEach(function(x){print(x.name)})')

if [[ -z $site_name ]] || [[ -z $site_id ]]
then
        echo "Error: AP found but unable to retrieve site information from UniFi database."
        exit 1
fi

# Find UniFi server hostname
domain=$(mongo --quiet --port 27117 --eval 'db.getSiblingDB("ace").setting.find({"key":"super_identity"}).forEach(function(x){print(x.hostname)})')
# Build URL
url="https://$domain:8443/manage/site/$site_id/devices/list/1/100"

# Output
echo "AP MAC: $mac"
echo "Site Name: $site_name"
echo "Site ID: $site_id"
echo "Site URL: $url"
